# prompts.py
# 在这里粘贴完整的 code -> prompt 映射字典
# edited 文件名后缀 (_035 这种最后的三位数字) 会作为 key 来查这个表
# key 必须是字符串形式 "001", "002", ... "099" ...

code_to_prompt = {
    "001": "Let the person wear sunglasses",
    "002": "Let the person wear a cowboy hat",
    "003": "Let the person wear a cap",
    "004": "Let the person wear earrings",
    "005": "Make the person wear a scarf",
    "006": "Make the person wear a suit and tie",
    "007": "Change the person's hair color to red",
    "008": "Change the person's hair color to blonde",
    "009": "Change the person's hair color to blue",
    "010": "Make the person have curly hair",
    "011": "Make the person look like a cyborg",
    "012": "Turn the person into a cartoon character",
    "013": "Turn the person into an anime character",
    "014": "Make the person look like a superheroe",
    "015": "Turn the person into a vampire",
    "016": "Make the person look like a ghost",
    "017": "Make the person look older",
    "018": "Make the person look young",
    "019": "Turn to be vintage",
    "020": "Turn to be modern",
    "021": "Turn to be medieval",
    "022": "Turn to be high-tech",
    "023": "remove the person",
    "024": "Make it look like the 1920s",
    "025": "Make it look like the 1980s",
    "026": "Make it look futuristic",
    "027": "Make it look like the Victorian era",
    "028": "Turn to an ancient Chinese style",
    "029": "Turn to a traditional Indian style",
    "030": "Turn to an ancient Egyptian style",
    "031": "Turn to a medieval European style",
    "032": "Turn to an oil painting style",
    "033": "Turn to a pencil sketch style",
    "034": "Turn to a watercolor painting style",
    "035": "Turn to a Monet-style watercolor painting",
    "036": "Turn to a Van Gogh-style painting",
    "037": "Change the background to a night scene",
    "038": "Change the background to a sunset view",
    "039": "Change the background to a forest",
    "040": "Change the background to a bright, snowy landscape",
    "041": "Change the background to an underwater scene",
    "042": "Make it look like a luxury brand advertisement",
    "043": "Make it look like a perfume advertisement",
    "044": "Make it look like a magazine cover",
    "045": "Make it look like an old, weathered paper",
    "046": "Make it look like an ancient manuscript",
    "047": "remove text",
    "048": "Add some water stains",
    "049": "Add some coffee stain",
    "050": "Add some blue ink stains",
    "051": "Add some scratches",
    "052": "Make the credit card look like a beautiful birthday card",
    "053": "Make the credit card look like a leather credit card",
    "054": "Make the credit card look like a golden engraved credit card",
    "055": "Make the credit card look like a handwritten love letter",
    "056": "Transform the credit card into a luxurious VIP membership card",
    "057": "Make the credit card look like a marble credit card",
    "058": "Turn the credit card into an elegant wedding invitation",
    "059": "Make the credit card look like a wooden carved credit card",
    "060": "Make it look like a wooden carved ticket",
    "061": "Make it look like a golden engraved ticket",
    "062": "Make it look like a marble ticket",
    "063": "Make it look like a leather ticket",
    "064": "remove the laptop",
    "065": "remove the plate",
}


def get_prompt_by_code(code: str) -> str:
    """code 是三位数字字符串, 比如 '035'"""
    return code_to_prompt.get(code, "edit the image")
